### ISSUE TITLE
complete ecu

### ISSUE THREAD

**Issue by geofrancis** [dadez87/Fuelino-SW-1.0-beta1#1]
is there anywhere to get one already complete, I think it would be a good addition to my cbf125 with 150 kit on it.

**Comment by dadez87** [comment]
Hello!

Thank you for contacting me.

I can send you one sample, if you help me with testing.
I am now in Italy but I will soon come back to Japan.

I also attach a presentation that will soon be available on my website.
Please check it out...

Where are you from? ;)

Davide

2016-11-20 0:30 GMT+09:00 geofrancis notifications@github.com:

**Comment by geofrancis** [comment]
I am from scotland, I currently do around 
26000km a year on my cbf125 riding year round.

**Comment by geofrancis** [comment]
edit
